### ISSUE TITLE
Maybe it's time to start releases?

### ISSUE THREAD

**Issue by chytreg** [lkankowski/arduino-multi-relay2#12]
Looks like recently we push forward some changes in devel branch that could be breakable.
Adding tags it's very simple and intuitive gives checkpoints where the code was stable. 
My proposal is to start tagging master alongside releases notes, and/or CHANGELOG.

Pls, consider it.

**Comment by lkankowski** [comment]
Sorry for late answer. I've messed up something in notifications.
I'll try to catch up all in next few days.

**Comment by lkankowski** [comment]
Tags and releases are great idea. I will do that with next merge of devel into master.
Regarding to changes on devel - not everything is merged into devel, because I didn't have time and refactoring was incomplete.
I also like to be the first tester in my house for a week or two - my wife not always likes this :D

**Comment by szurr** [comment]
Best regards for wife 😜
